export const API_ENDPOINTS = {
  MATRICULAS: {
    CREATE: '/matriculas',
    GET_ALL: '/matriculas',
    GET_BY_ID: '/matriculas',
    UPDATE: '/matriculas',
    DELETE: '/matriculas'
  },
  PARAMETROS: {
    CREATE: '/parametros',
    GET_ALL: '/parametros',
    GET_BY_ID: '/parametros',
    UPDATE: '/parametros',
    DELETE: '/parametros',
  },
  INDICADORES: {
    CREATE: '/indicadores',
    GET_ALL: '/indicadores',
    GET_BY_ID: '/indicadores',
    UPDATE: '/indicadores',
    DELETE: '/indicadores',
  },
  CALIFICACIONES: {
    CREATE: '/calificaciones',
    GET_ALL: '/calificaciones',
    GET_BY_ID: '/calificaciones',
    UPDATE: '/calificaciones',
    DELETE: '/calificaciones',
  },
  CARGA_ACADEMICA: {
    CREATE: '/carga-academica',
    GET_ALL: '/carga-academica',
    GET_BY_ID: '/carga-academica',
    UPDATE: '/carga-academica',
    DELETE: '/carga-academica',
  },
  MATERIAS_AREAS: {
    CREATE: '/materias-areas',
    GET_ALL: '/materias-areas',
    GET_BY_ID: '/materias-areas',
    UPDATE: '/materias-areas',
    DELETE: '/materias-areas',
  },
  GRUPOS: {
    CREATE: '/grupos',
    GET_ALL: '/grupos',
    GET_BY_ID: '/grupos',
    UPDATE: '/grupos',
    DELETE: '/grupos',
  },
  USUARIOS_COLEGIO: {
    CREATE: '/usuarios-colegio',
    GET_ALL: '/usuarios-colegio',
    GET_BY_ID: '/usuarios-colegio',
    UPDATE: '/usuarios-colegio',
    DELETE: '/usuarios-colegio',
  },
  AUTH: {
    LOGIN: '/usuarios-colegio/login',
    RENEW_TOKEN: '/usuarios-colegio/renovar-token',
    LOGOUT: '/usuarios-colegio/logout',
    RECOVER_PASSWORD: '/usuarios-colegio/recuperar-contraseña',
    RESET_PASSWORD: '/usuarios-colegio/restablecer-contraseña',
  },
  DIRECCION_NUCLEO: {
    BASE: '/direcciones-nucleo',
    LOGIN: '/direcciones-nucleo/login',
    CHANGE_PASSWORD: (id) => `/direcciones-nucleo/${id}/cambiar-password`,
  },
  COLEGIOS: {
    BASE: '/colegios',
    BY_DIRECCION_NUCLEO: (id) => `/direcciones-nucleo/${id}/colegios`,
  },
  SEDES: {
    BASE: '/sedes',
    BY_COLEGIO: (id) => `/colegios/${id}/sedes`,
    ACTIVATE: (id) => `/sedes/${id}/activo`,
    DEACTIVATE: (id) => `/sedes/${id}/desactiva`,
  },
  VIGENCIAS: {
    BY_YEAR: '/vigencias/año',
    ACTIVE: '/vigencias/activa',
    BASE: '/vigencias',
    ACTIVATE: (id) => `/vigencias/${id}/activar`,
    DEACTIVATE: (id) => `/vigencias/${id}/desactivar`,
  },
  PERIODOS: {
    BASE: '/periodos',
    BY_YEAR: (year) => `/periodos/año/${year}`,
    ACTIVATE: (id) => `/periodos/${id}/activar`,
    DEACTIVATE: (id) => `/periodos/${id}/desactivar`,
  },
};